class LuoTianyi:
    name_ch = '洛天依'
    name_ja = 'ルオ・テンイ'
    name_en = 'Luo Tianyi'
    birth_m = 7
    birth_d = 12
    birthday = '07 12'
    age = 15
    color = '#66CCFF'
    cv = '山新 鹿乃'
    group = ''
    img = 'https://img.moegirl.org/common/3/38/Carton-new0.png'
    source = 'https://zh.moegirl.org/洛天依 https://baike.baidu.com/item/洛天依'
class Miku:
    name_ch = '初音未来'
    name_ja = '初音ミク'
    name_en = 'Hatsune Miku'
    birth_m = 8
    birth_d = 31
    birthday = '08 31'
    age = 16
    color = '#39C5BB'
    cv = '藤田咲'
    group = 'Crypton Future Media'
    img = 'https://img.moegirl.org/common/9/9b/Hatsune_miku_v4x.png'
    source = 'https://zh.moegirl.org/初音未来'
class YuezhengLing:
    name_ch = '乐正绫'
    name_ja = '$UNKNOW$'
    name_en = 'Yuezheng Ling'
    birth_m = 4
    birth_d = 12
    birthday = '04 12'
    age = 16
    color = '#EE0000'
    cv = '祈Inory'
    group = 'Vsinger'
    img = 'https://img.moegirl.org/common/8/84/YUEZHENGLING.jpg'
    source = 'https://zh.moegirl.org/乐正绫'
class YanHe:
    name_ch = '言和'
    name_ja = 'イェンホー'
    name_en = 'Yan He'
    birth_m = 7
    birth_d = 11
    birthday = '07 11'
    age = -1
    color = '#00FFCC'
    cv = '刘婧荦'
    group = 'Vsinger
    img = 'https://img.moegirl.org/common/8/84/YUEZHENGLING.jpg'
    source = 'https://zh.moegirl.org/言和 https://baike.baidu.com/item/言和'